### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by junocomp** [droidian-devices/linux-android-google-sargo#2]
I found this the other day, I am not sure if is already integrated in the current Drodian sargo kernel. 

https://android.googlesource.com/device/google/crosshatch/+/master/sdm845/kernel-headers/media/cam_req_mgr.h

As far as I can see, this is the camera driver for the phone.

**Comment by erikinkinen** [comment]
This is for a different device: crosshatch

**Comment by junocomp** [comment]
@erikinkinen you're right. I didn't see that.

**Comment by junocomp** [comment]
What about this?

https://developers.google.com/android/drivers#bonito

**Comment by erikinkinen** [comment]
Those are the files put onto vendor partition.
